#include "Tokens.h"

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(HdNeVKSettingsTokens,   HD_NEVK_SETTINGS_TOKENS);
TF_DEFINE_PUBLIC_TOKENS(HdNeVKNodeIdentifiers,  HD_NEVK_NODE_IDENTIFIER_TOKENS);
TF_DEFINE_PUBLIC_TOKENS(HdNeVKSourceTypes,      HD_NEVK_SOURCE_TYPE_TOKENS);
TF_DEFINE_PUBLIC_TOKENS(HdNeVKDiscoveryTypes,   HD_NEVK_DISCOVERY_TYPE_TOKENS);
TF_DEFINE_PUBLIC_TOKENS(HdNeVKRenderContexts,   HD_NEVK_RENDER_CONTEXT_TOKENS);
TF_DEFINE_PUBLIC_TOKENS(HdNeVKNodeContexts,     HD_NEVK_NODE_CONTEXT_TOKENS);

PXR_NAMESPACE_CLOSE_SCOPE
