# This is a basic workflow to help you get started with Actions

name: CI

env:
    BUILD_TYPE: Release
    VULKAN_SDK_VERSION: 1.2.189
    EMBREE_VERSION: 3.13.1

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Create Build Environment
        run: |
          cmake -E make_directory ${{github.workspace}}/build
          cmake -E make_directory ${{github.workspace}}/build/deps
          choco install wget

      - name: Download Vulkan SDK
        shell: bash
        working-directory: ${{github.workspace}}
        run: |
          mkdir VULKAN_SDK; cd VULKAN_SDK
          mkdir build; cd build
          git clone https://github.com/KhronosGroup/Vulkan-Headers.git --branch sdk-${VULKAN_SDK_VERSION}
          git clone https://github.com/KhronosGroup/Vulkan-Loader.git --branch sdk-${VULKAN_SDK_VERSION}

      - name: Install Vulkan SDK Headers
        shell: bash
        working-directory: ${{github.workspace}}/VULKAN_SDK/build/Vulkan-Headers
        run: |
          cmake -DCMAKE_INSTALL_PREFIX=../.. -DCMAKE_BUILD_TYPE=Release .
          cmake --build . --config Release
          cmake --install . 

      - name: Install Vulkan SDK Loader
        shell: bash
        working-directory: ${{github.workspace}}/VULKAN_SDK/build/Vulkan-Loader
        run: |
          cmake -DVULKAN_HEADERS_INSTALL_DIR=../.. -DCMAKE_INSTALL_PREFIX=../.. -DCMAKE_BUILD_TYPE=Release .
          cmake --build . --config Release
          cmake --install . 
          export VULKAN_SDK=${{github.workspace}}/VULKAN_SDK

      - name: Setup Embree 
        working-directory: ${{github.workspace}}/build/deps
        run: |
          wget https://github.com/embree/embree/releases/download/v${env:EMBREE_VERSION}/embree-${env:EMBREE_VERSION}.x64.vc14.windows.zip
          7z x embree-${env:EMBREE_VERSION}.x64.vc14.windows.zip -y

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: >
          cmake -A x64 ${env:GITHUB_WORKSPACE}
          -DCMAKE_BUILD_TYPE=Release 
          -Dembree_DIR="${env:GITHUB_WORKSPACE}/build/deps/embree-${env:EMBREE_VERSION}.x64.vc14.windows/lib/cmake/embree-${env:EMBREE_VERSION}"
          -DVULKAN_SDK="${env:GITHUB_WORKSPACE}/VULKAN_SDK"

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --config ${env:BUILD_TYPE}
